import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
    ClerkProvider
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/Header";
import colors from "@/colors";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Expense Tracker App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    style={{ backgroundColor: colors.background }}
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Toaster richColors />
                    <Header />
                    <main className="min-h-screen">
                        {children}
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
